### ISSUE TITLE
Changes for next version

### ISSUE THREAD

**Issue by debaal** [debaal/SolderingIron#12]
- Add Cap (100nF) to AREF pin
- Check collision of parts (especially overlapping)
- Change pin for PWM of soldering iron to a pin connected to an 8-bit timer output
- Simplify Layout and create a THT version for users with no SMD experience. 
- Add an optional FTDI for debugging
- Add an optional ESP8266
- More Buttons for Presets

**Comment by oni303** [comment]
"Change pin for PWM of soldering iron to a pin connected to an 8-bit timer output"
that one is no longer valid in my opinion.

**Comment by oni303** [comment]
is it possible to add a lable hardware?

**Comment by debaal** [comment]
made two new issues taggeg with BUG and ENHANCEMENT
