### ISSUE TITLE
Optional Hardware Changes

### ISSUE THREAD

**Issue by debaal** [debaal/SolderingIron#18]
- ~~Change pin for PWM of soldering iron to a pin connected to an 8-bit timer output~ (see commit dfee941ed4c49ba38832c4c0dd414090535b01d2)
- ~~Add an optional FTDI for debugging~~ (UART is available and an FT232 does not fit on the board)
- ~~Add an optional ESP8266~~ (an ESP8266 can be wired to the UART and it does not fit onto the board)
- ~~More Buttons for Presets~~
- ~~Free SDA/SCL pins from display in order to connect I2C~~ (see hardware v1.2 in bc359611b22779060904d67200dcd036d9aafa12)

**Comment by kartenkarsten** [comment]
FTDI with bitbang mode for (inital) programming would be nice.

**Comment by yschroeder** [comment]
This is not a dev board but a soldering station. I think a user of this project will likely get a proprogrammed avr and the ability to reprogram it via a dedicated programmer.

**Comment by kartenkarsten** [comment]
Sure - it depends if there will be a shop selling this hardware - or if a customer has to order all parts by himself. Not every one soldering has AVR experience.

**Comment by yschroeder** [comment]
Yes, we have to define who is the target audience for this project and how it can be delivered to a interested user. Depending on that we are able to make assumptions on what the user will be able to handle himself and what must be done before he gets a kit or however this project is shipped.

**Comment by debaal** [comment]
Maybe we offer packages (for a slightly higher price) with preassembled and tested critical parts like the AVR, FETs, SMD Cs/Rs. This way we can flash and check the AVR. All bigger parts (LM324, LDO, THT parts) can be assembled by the user of course.
