### ISSUE TITLE
Update ADC library

### ISSUE THREAD

**Issue by yschroeder** [debaal/SolderingIron#27]
The ADC library should not measure the tip temperature free running as stated in #26. The solution is to let the PID controller trigger the adc measurement when the heater is off. The PID controller will continue its work on the ADC conversion complete interrupt.

Things to change:
* do not measure the tip temperature free running
* no need for averging any more
* do nothing when the conversion is completed, the PID controller will handle this

Maybe we should not scrap everything unneeded from the library, AFAIK the hall sensor needs the ADC too and it may be valid to use free running mode there...

**Comment by kartenkarsten** [comment]
already improved
