### ISSUE TITLE
More intelligent PID controller

### ISSUE THREAD

**Issue by yschroeder** [debaal/SolderingIron#42]
While discussing PR #40, I had an idea:
It was observed that the ADC readings for the tip temperature are too high when the tip is heated as predicted in issue #26. When the ADC reading while heating does not exceed the maximum value it may be possible to calculate accurate temperatures even while heating. There would be a need to sometimes measure without heating to have a baseline temperature. Then it might be possible to measure how much the ADC value rises while heating. It may then be possible to compensate this excessive voltage in software and allow the PID controller to not disable the heating when it needs a new ADC value. This can increase the possible PWM duty cycle.

**Comment by oni303** [comment]
This is not possible. The opamp goes into saturation when the tip is powered. Thus no measurement is possible during powering.
Furthermore, the very short duration of the measurements do not hold the tip from heating.
