### ISSUE TITLE
change the 6pin header

### ISSUE THREAD

**Issue by debaal** [debaal/SolderingIron#60]
change the 6pin header so that vcc for the hall sensor is on that same header and the tip does not need two pin header on the pcb if the hall sensor is built into the handle

**Comment by kartenkarsten** [comment]
as an alternative the hall sensor could placed inside the tip holder and magnets inside the handle

**Comment by debaal** [comment]
I know, but after some discussion we agreed to not make wires to the tip holder necessary. Yes it is an option, but I think this way we have less wires.

**Comment by debaal** [comment]
done (see b27c82880ccd5efc92a7d6ddf00b78ccccea0d28)
