### ISSUE TITLE
display dark after a while

### ISSUE THREAD

**Issue by oni303** [debaal/SolderingIron#62]
Sometimes I observe a strange behavior of the display.
After some time the display suddenly is off.

**Comment by debaal** [comment]
Did anyone reproduce this by now?

**Comment by oni303** [comment]
No maybe it was a bug in the test code of the controller. After I started to implement the main program I have not seen it again.

**Comment by yschroeder** [comment]
Haven't seen this on crunch day.

Should we close this?

**Comment by debaal** [comment]
Yup!
