### ISSUE TITLE
Rearrange pinout

### ISSUE THREAD

**Issue by yschroeder** [debaal/SolderingIron#64]
The 328p in TQFP has two ADC pins that are not present on the PDIP package. For the sake of simplicity for the design of the THT version (see #21) these pins should not be used. This will break software compatibility.

The hall sensor should be remapped to ADC1 oder ADC2 (what is the purpose of these two currently anyway?).

The display FETs should be switched to PD5-PD7. This frees up the I2C, which should be mapped to some pins for future use. Also include +5V and GND on this I2C header. Don't forget the pullups.

Those changes should then be made to the currently used development boards and documented in the wiki. Then change the code accordingly.

**Comment by debaal** [comment]
should be changed as described in commit 5cac9fd33575695e9156b7c23c9f8853ad347457.

i2c pull ups are 10k right now
