### ISSUE TITLE
Suitable Power Connector

### ISSUE THREAD

**Issue by debaal** [debaal/SolderingIron#72]
2.1mm and 2.5mm power jacks allow up to 3A.
That is half of what we need. Any ideas?

**Comment by yschroeder** [comment]
Well, they sell power supplies with that connector and 6A, but don't sell jacks with the same rating? This does not make sense...

Our system does not draw 6A all the time, only for a few seconds when heating up. I think going with the connectors can work for now.

**Comment by debaal** [comment]
I assume this is solved then and I also assume that the 3A limitation is meant for a sustaining current. So we'll stick to the 2.1mm power jacks.
